apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: app-nodejs-build
spec:
  params:
    - description: GitHub source code repository URL
      name: gitUrl
      type: string
    - description: GitHub branch
      name: gitRevision
      type: string
  steps:
    - image: >-
        registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8:v1.6.2-21
      name: git-clone
      resources: {}
      script: |
        #!/usr/bin/env sh

        echo "------Cloning source code repo-------"
        git clone -b $(params.gitRevision) $(params.gitUrl) ./ || exit 1
        echo "-------------------------------------"
      workingDir: $(workspaces.doc-source.path)
    - image: 'node:16-alpine'
      name: run-tests
      resources: {}
      script: |
        #!/usr/bin/env sh
            
        echo "--------Running Test cases---------"
        npm i jest
        npm run test || exit 1
        echo "-----------------------------------"
      workingDir: $(workspaces.doc-source.path)
  workspaces:
    - name: doc-source
