apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temperature-converter-app
spec:
  destination:
    name: ''
    namespace: ''
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: ''
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - Validate=false
